name: LSIF
on:
  push:
    paths:
      - '**.go'
      - 'go.mod'
      - '.github/workflows/lsif.yml'
env:
  GOPROXY: "https://proxy.golang.org"

jobs:
  lsif-go:
    if: github.repository == 'sourcegraph/docsite'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate LSIF data
        uses: sourcegraph/lsif-go-action@master
      - name: Upload LSIF data to sourcegraph.com
        continue-on-error: true
        uses: docker://sourcegraph/src-cli:latest
        with:
          args: lsif upload -github-token=${{ secrets.GITHUB_TOKEN }}
      - name: Upload LSIF data to S2
        continue-on-error: true
        uses: docker://sourcegraph/src-cli:latest
        with:
          args: -endpoint=https://sourcegraph.sourcegraph.com lsif upload -github-token=${{ secrets.GITHUB_TOKEN }}
